replicaCount: 1

image:
  registry: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com
  repository: quay/prometheuscommunity/yet-another-cloudwatch-exporter
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: yace

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  allowPrivilegeEscalation: false

configMap:
  enabled: true

config: |-
  apiVersion: v1alpha1
  sts-region: ap-northeast-2

  discovery:
    exportedTagsOnMetrics:
      AWS/ApplicationELB:
        - Name
        - Environment
      AWS/RDS:
        - Name
        - Environment
      AWS/ElastiCache:
        - Name
        - Environment
      AWS/NATGateway:
        - Name
        - Environment
      AWS/S3:
        - Name
        - Environment
      AWS/WAFV2:
        - Name
        - Environment

    jobs:
      - type: AWS/ApplicationELB
        regions:
          - ap-northeast-2
        metrics:
          - name: RequestCount
            statistics: [Sum]
            period: 60
            length: 300
          - name: TargetResponseTime
            statistics: [Average, p95]
            period: 60
            length: 300
          - name: HTTPCode_ELB_5XX_Count
            statistics: [Sum]
            period: 60
            length: 300
          - name: HTTPCode_Target_5XX_Count
            statistics: [Sum]
            period: 60
            length: 300
          - name: HealthyHostCount
            statistics: [Minimum]
            period: 60
            length: 300
          - name: UnHealthyHostCount
            statistics: [Maximum]
            period: 60
            length: 300
          - name: TargetConnectionErrorCount
            statistics: [Sum]
            period: 60
            length: 300

      - type: AWS/RDS
        regions:
          - ap-northeast-2
        metrics:
          - name: CPUUtilization
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: DatabaseConnections
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: FreeableMemory
            statistics: [Average, Minimum]
            period: 60
            length: 300
          - name: FreeStorageSpace
            statistics: [Average, Minimum]
            period: 60
            length: 300
          - name: ReadLatency
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: WriteLatency
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: ReadIOPS
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: WriteIOPS
            statistics: [Average, Maximum]
            period: 60
            length: 300

      - type: AWS/ElastiCache
        regions:
          - ap-northeast-2
        metrics:
          - name: CPUUtilization
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: EngineCPUUtilization
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: DatabaseMemoryUsagePercentage
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: CurrConnections
            statistics: [Average, Maximum]
            period: 60
            length: 300
          - name: Evictions
            statistics: [Sum]
            period: 60
            length: 300
          - name: CacheHits
            statistics: [Sum]
            period: 60
            length: 300
          - name: CacheMisses
            statistics: [Sum]
            period: 60
            length: 300
          - name: ReplicationLag
            statistics: [Average, Maximum]
            period: 60
            length: 300

      - type: AWS/NATGateway
        regions:
          - ap-northeast-2
        metrics:
          - name: ActiveConnectionCount
            statistics: [Maximum]
            period: 60
            length: 300
          - name: BytesInFromDestination
            statistics: [Sum]
            period: 60
            length: 300
          - name: BytesOutToDestination
            statistics: [Sum]
            period: 60
            length: 300
          - name: PacketsDropCount
            statistics: [Sum]
            period: 60
            length: 300
          - name: ErrorPortAllocation
            statistics: [Sum]
            period: 60
            length: 300
          - name: IdleTimeoutCount
            statistics: [Sum]
            period: 60
            length: 300

      - type: AWS/CloudFront
        regions:
          - us-east-1
        metrics:
          - name: Requests
            statistics: [Sum]
            period: 60
            length: 300
          - name: BytesDownloaded
            statistics: [Sum]
            period: 60
            length: 300
          - name: BytesUploaded
            statistics: [Sum]
            period: 60
            length: 300
          - name: TotalErrorRate
            statistics: [Average]
            period: 60
            length: 300
          - name: 4xxErrorRate
            statistics: [Average]
            period: 60
            length: 300
          - name: 5xxErrorRate
            statistics: [Average]
            period: 60
            length: 300

      - type: AWS/S3
        regions:
          - ap-northeast-2
        metrics:
          - name: BucketSizeBytes
            statistics: [Average]
            period: 86400
            length: 172800
          - name: NumberOfObjects
            statistics: [Average]
            period: 86400
            length: 172800

      - type: AWS/WAFV2
        regions:
          - ap-northeast-2
        metrics:
          - name: AllowedRequests
            statistics: [Sum]
            period: 60
            length: 300
          - name: BlockedRequests
            statistics: [Sum]
            period: 60
            length: 300
          - name: CountedRequests
            statistics: [Sum]
            period: 60
            length: 300
          - name: CaptchaRequests
            statistics: [Sum]
            period: 60
            length: 300
          - name: ChallengeRequests
            statistics: [Sum]
            period: 60
            length: 300
