apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC2okmXP7+6f2nriGoHWi7wufkeLyfhW4vfn1jbVLFecRdY/+PGGzh7W48T9IckOMBjaBl2IbVXvWxmw2JBz+UMNcyaVe0TVoGipU3YlMzx9fpSeDf84pMv4GEEPCTi4aeuW37SoOk2BxxTb5hoQ13RM1qYPILSprO5UUu4PpI5H+5pJHNo9SMGN4p7DHcNr51d2OqLrXByK5C+YP1g4kOEspRp6NGkQANeYR42RsfEKclT12f0pXJha4We1rmkjPGuFbXbEIHfjjHBG4Ys+iow1Gc42TBZCBz/1itm0l12uSWtUaJoDtcdsurgAoXZwyYHaQ2Kj8HyyWJFKgeNsIj7gsvO0f6a98sScNrj1WFDo1j/BFW2PFySkJWzLxlbbJIomMeKjLvq/1VzUuk667Zkrur1Aw9tmpZ1Q4fGo/gILu8FGBTg49gHc/aJ5Vnq44cSEacY/WSebPzavmIAIVt1hBqqWL08RaXiDNseBt1RYuD3d6G2gqfmahMwfUkFwMLyuDNIeuEWiHxylw3TYKfRBqaI9cRH+cedWrbQvnlXN6PmwFiMFAVP/Q0JL0GPUo0z0kqa5QnbzBUAQIiTtnBuwGhXwrFprYpfk7uOBLnN3ILrUvyKpOdmwGBiA+co8YBKRxA+gZkNtegBj3A6ZyXf0OL5ykukEcaITtOyT0XJc+GmQWvFeMmYYiFIFxWI5HcvJJtLZGcOCoSZFyrxGmTECs3szowU0Ac3mpvG3Tcb1Bh+ZSw4mRfh
    admin-user: AgBbJiLX0iKgo1L9xITFQYP9EkFV6J6uZ1btXxUOD8ttyi1P45HA78EMEGuBmQkQiV0/gVG6BzeL3aUGthM4Sm+3aYfoWCJTonxw+Bnn2bg/q9SJgLEqCrR7v1jCazl/h5oDxiktWQa5+FNdcXNj+/AIr60/UEFP+S1Gn61ITWstZI2BgfWy/FmSDAU8wz58YdpedUzCFN3VmAjPitPpkV4NoNbRQLcbZlQwwWKw1qaEZUuxH3n34rt1CN4CDGInMYGhDKZ0jU7vlPBWhba9TZ26lQBpxlhokURX8XXOPY8lUw8NLwHN3FyCi/PxlGd9YH9DoB2foaMYB8zU4GzyxpsWwSip2mYUF1ygcn0lwmleDv4bu5yuZuz3ZOt/Qtu8XFOf2t+hKJAy4lygkQkRLLleGpxssYCUvQRxVzStxj7WbhP+phzi90VSVgjUCzPE4NajhU5MmoxqU5GADdwDYpqS6Fzl4MxYjeQdGNpiiF4vEJs8xWwJ7/grorWp3X8tO81f4tNV8SvnQkL/AARFvtdE9o3OKu98IOq7ieRZoq5AuMu3G2kV91D1V/lcqT0K1LHZKrVk9vIYR43hsmZuFros1Vk4UrEjdwYCa/Tjg0ZmZQ7w+Zu67A8IttxPuxYjXF9MEnA+NEpVfVcpDVv/R8fny7RzOPaMRaXtKXfPanty6ke201JLyTD9U7lCMZ67FVbke7xIMQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
