provider:
  name: aws

serviceAccount:
  create: true
  name: external-dns

sources:
  - gateway-httproute

env:
  - name: AWS_DEFAULT_REGION
    value: ap-northeast-2

domainFilters:
  - hive-wiki.com

policy: upsert-only

registry: txt
txtOwnerId: hivewiki-dev

image:
  repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/k8s/external-dns/external-dns

nodeSelector:
  env: shared
  workload: system
