apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - sealedsecret.yaml

images:
  - name: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/hivewiki-collector
    newTag: dev-8f7fd7c
