---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hivewiki-collector-dev-secret
  namespace: hivewiki-collector-dev
spec:
  encryptedData:
    DB_PASSWORD: AgBqnialY+NIMDuqxCRXLVpB5qqwi7uBL10Kzg56UpdFr0Jwa5v2+MhdZgBLSj7zWG+jnpsIjKdxwMEOh0oZIv08akN95qdY9OeNvisKS0HrPG8ueYG4j7V03segpoHVV4z3Ogtg4zDBz7FMjtZvFUFaw5/6JEtjaQTUYIoFTUSC8CdMCRuxt25GQfTViHRLI6YOy5vdeZAfYN9H6hll6QOvkaZFqf31cDJ3led2jU1ElmrT3wRQE2mlcrp2NSOCCYaoe8cz/QZ0tfjSH1Zrxntz0GHK9RdDbdKHfOTMDFXSNOZRdfHX/YXQz4RJKcBXVrud6QXhEiIs62xYxslMIQyvoYZXtg688i3/eSu4DOOv+B2IaacZJXDintOeKjItJ0cB+kgrIrP/RzMg9r7kY5n4HMUm8tBMo1QhOeWU3NpBHaFktY06yJuduCKgvTWC+FHNQsrdqHojF2LOGkk6Crg8i40xjwcGb6Ts9GQgCO9HdR761Ex/ZipEgmrTAvPAwGLl/wW7PvZws0pwCkJMkujzOFF8zyRRiYMBG3aqD40ihESeHJhBtKYJGBKIjPG8ZCAosQeBcybO9auNaJTlDu3o28RxMuKXnM5zPFwkOcTVDINmvfIo+lryBAjTHmkDqfoAqTp4F59mpdvTk3IqH0dizkjYbj66+Q7j7tr9V21iotsu7AufRO+1xIUccNjkfCyMCuXY+AuC83bH6iJ8YA==
    REDIS_URL: AgCF6UZavifFvH9hFLjTUU+DFfN7qDGLSP3b/NTdo7qvaN2HirIeA/p1kUl5MQCqlU8dx7vMnpT9C2EUW0/XuyJhqhfnAW3JRiyhaCHB3Aq2HIAr1ME/zTz9+RTbwuqOwaMsAeOqPRBzUo5isQjpUGz8IT2tboXguDAF4JFad5BPXiZEQLcHYOgj9yn9EbeKIrWExul7Hqz54AsZMG+VqEPD6gNcbS+Gsh22hEEi8nvAz4FXg6ISwgAEC/beiG2bGMI5vrtiur5thDmfQxqFhprMfOu54cOYxfp2TVWhSGmpeMHidoQWEOssMD9Y9rukpVvuce++L243+SjON5CLhAZUlnxw1keW/oDOAruTXnMWu45YBG561BvVu+S2CoWQIWuXCTuGmcQP58RU7i8h131BoGEI5NscN0kJxhAf+nP+r15rt+3ARsMGKD2Plz8rxmyQNkZT0R7K3uIEwj/8slEgmsJKb3Gv4O9/dWCWYVABkR7X3xHuVq1ntp/DLbL4pmszsMohY5HK9RiUub3QLObiCDWAvkeCdOIy5WTY5nCxT77/78l4P314i7gNZGViUqIYH3kz0VrzttZ3t6v0hrVZSE/dZqZCnZY8cqJUj83uGNKsn5xVHgnUBfCSXFn9TQiTN+sjjcNZieMFScHikUUbZYU8FaxaI1BxqgOmQyR2C+nA6K6fAjQ5liBvsQR1WGZsnOmJdyXCBvGZEMKIKKEGYidp3MrDrco6lsizL1mJjZwfhGp+vOS/6a0Bq95oX5JwAgSG5es+FRpSAwHp6ah9y0E=
  template:
    metadata:
      name: hivewiki-collector-dev-secret
      namespace: hivewiki-collector-dev
    type: Opaque
