---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hivewiki-collector-dev-secret
  namespace: hivewiki-collector-dev
spec:
  encryptedData:
    DB_PASSWORD: AgBYwJolpwhagPZfP9zX8P7h2IanQhrUX6p/t6UhXy07wBsDyecYt/YDkGeD0iIr0UIY9nTnRjSk2h+vb793AnSwlvGfbgCgZ8UPsqUIQCIWs22Pcqz/5I1Sskbw4EKNNELj6TByqTCHqwhwzQTqYq1bsP6c1l0HSHug93STMkztzJUZbnJdmcnMpyhR0brbuOozsaQJD1pfdbyM7ylzH7WI5AZr5l/yGrM03hDIgzQP7T6Nev3rSi/ZjXZmmBQ0AtOqsrrJ8V3zvw/u7JcJn8WoWcuVZOtJNCbYq+hPRfFWKCP+SF9vvgGdxrZCS1V4s6LcpNHv2DIANI48cjvDxqbq0DWw87LFCx2FWauXPMZoS3Q5Vw3U0ixJ1nlZ10nigPLBTf+kWXByBHaKuaVBNDap5StPwkdBPFBIcROk1aV0GEfUwXtSrTDsOXf2GuaqWVlOsxaS5kLpLNCS8NjLsTNVJFL5yODjXEZRkO1GRfiES3cANGBwg4K2RIVYgObtVEJ2yLKkxgPZYkaNwqcp6uv0fj1D+VJDe/CFv+d7bPz/7b2eeiQ/YvOtRKpYMd4UBdJxQ+F03u98PuD33D894K5o1d9Z4Q8zIT0+wWOAAe1yjEdzVhVn0cHLNxTjTSbV58PTU/i0JGXU9M1TR0OJ7Uxth7IuOqS9526SgBHHpUkAQMnzq3aoUHQptF1Q8ODDNkH3aLe9AUxcw92EesUXiQ==
    REDIS_URL: AgB15VqDXHf1iFvfsMmKbA78mTz52qzmyoVa0h3CLrMb0mJ6Yv+RrdfXMCflrhqzM9hiO7sHvgj+qAZ4dKQHRmQ5spjxzKz39xIYac0fuE1BZBkUCwmvmN3ZEpAB8WuIwAmWdA1CEiOMp9Vsja3rlb6WAvCo+durQtDPypNp3g4Q5qRa3b20Y4Tvhw0z8unxSogIa7BsWER3HF3KziQvt9wyd/6LlUblIrcYxa89I3JHJ6Ya3ZhbxhgvJk0tCnlR29bJqmuEVmKw3cNyR4Qni1vcNHiTZOqCIDsRXOnedRVtBrWJZ6bBNCHckI4vzh9QYJkUyTTKkTLyfaeogVQWXzYcqNmps+7Kam0qnjBDXE90cY9TVAyVPRBp7pEBW/8VNdqYBf7fA3f4IiqBJtP1ILGP9aRXv612sV0IzJpvp5i/KDNsfekba2eeU+TrKD3f1zV30mHPcFEFNNiP73KSsvp7WZgVQ1eijelB8ll8xIbyUxrljkxRpVnXH2kV4naXPipyWyhfAVOPyV95DP5IPHbPQHeNVE/j2b2ZL3c8nChKGMcKVYP1qDPJgRKy4b0gEYTq0dTQLl5f7x2i9cQZnJrpp0AmSbT3g7xVzUvQ4UWLHvPae4f9gxhib+HZ6o+H5iM25ArdKVYcs+Nb6A+pIML/1tI03G+mwcMQEeBHw1nSSy4eMw3u88yaKVeTwVqVyFySn0dR+QG6i8FcGh4zRMWOq953oCAFLtAt5UGQP7Lej0s0Cpj/qEbP8SzxK527ixiWeTp+L2KF/mdVPf8MFKxbUw==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hivewiki-collector
        app.kubernetes.io/part-of: hivewiki
        environment: dev
      name: hivewiki-collector-secret
      namespace: hivewiki-collector-dev
    type: Opaque
