---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hivewiki-collector-dev-secret
  namespace: hivewiki-collector-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCP0OFFdf+TPUi17G3wtxRjRFU9TW1Fkt7gSlXuXr7PdVV6Z6OGaTZc65YAbx2S9m8jgQtvM3KFnMb/PJlg3iwLEzmyf7NUXishEyxuvRm7+jtTSx7fUs2YVPr0wg+oZLYpX1v64ETckEELPQRJZVNNREl2RIFkr29jiWOgkW68iFmrdzF2S/FVZP8iv380eTR1prP4tBu/yeBassKULHvZatd7kIh6ZgVzKS1joTZfP74xC3EmUDzzC5mg4fm5WvnHHP3kLxWPjRlgsDeCZTA+L29jAh/K3OhGhcVCkcGpx4PJkwD2WZa+J2i/aPwKq8vU7pqpQ+34dIUJ9tgAK7lvMcqzH6KW9+bRbuhnpq3NegpjH/U29r9zRd79OBFwlSLr+Hx3Q0KOzUq4BxZQ1r1ft6iGtFnD0Flm8q4GojzcIzQWE1OHieQyW+wpFXDoVHf9AcNzijq5cR3mJqwvSvaeeH/mBtVYwfNlj8COqdMUuz6H8P/mE9Wo9Gbpydlsc0rL1xCIeBXX6Fvr68YjW1+L/d7D4rRhLfnw16FYEEEBZs+45k/HrwmzwQ2pCUcap5DRc50r/D76twIWqwYOS/ftdukeQRwYsSJtSg4Y/ITP/pDoauialnmwnK5a9uFt8/LMSZ7HTQVUdjEabixt0/TW3aTo25YOq35vnE7o3q100TfcKwRptweJe4PhX9Pyj09oxSBgP0IX2uaJQrSpnA==
    REDIS_URL: AgA79586Q6T2fX82py+TtZ02t20Y/zxux/AC9lXTJyFzaPflpSfl3vtWWpNMPw2aZCZpxnZsKrkH9St7xG2t8zJDejfN+/dZ0QUeJrTFYpHjNMjZvJq2ka5+WDd900MYFJAJKuFoByt18HUSKP9G9Ojg+HVImVlkhUuOA+Zg7F1LcLnS2ZQELNCcCHTUNNek5y1/TuL88uQ+2WnUHBn3d+wNW4dLA1Mm7+04uk7P4S4wSXRDGmdyF6GlnCjTsY4AIXQlyO9KDjxp14dA2jHQRwPFdj+y3BZ10hodsAG1gpqqpEdH/qR8Ekx8fEz0Mhq0Q9oHmzXAg86D5iBlWQIGZS0i5gWlEfr0zNhPA0ae/4+RsKgSUu/hWhq6lUX4w67dtahWdyJxIC9BIG9+FxgOyZi7x/iC21gXaGAYUmXUmAYCOfKkzqXHgdHR4SirR5dVs3I2wck4anEFvrfAP2WBfqnXhhc5zO1OEnhzKzpwjyVhns0eymxNdhgqP1juSPW+1SOOSXkncgRQdnoCNOqMek3QpszwPP42qRHapl/7Teje7y83bLVsLA/yUmB2H0imdRrG2PpCOi0altrCPe4B4G5uim/4aTltB1+rYndxlPg5ZWaA9h8Clk4TTqM01+7k2qtikghkLrJ7Z7pg2gIsONlS3kJ+h3azAwuJGg2kH4fSgONFjXZ7oh+AknsRGM3EVc6iw3lNRS/uAt432ZQOBHmo8dXC+sS4BCWQva1LiIAXEUDzzvPPVl/JMTdif4SicU+qiFgYXZwX0MLozVySL7mXWQ==
  template:
    metadata:
      name: hivewiki-collector-dev-secret
      namespace: hivewiki-collector-dev
    type: Opaque
