apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-kube-green-placeholder
    receivers:
      - uid: slack-kube-green-placeholder
        type: slack
        disableResolveMessage: false
        settings:
          recipient: "#alerts"
          url: $GRAFANA_ALERTING_SLACK_WEBHOOK_URL

policies:
  - orgId: 1
    receiver: slack-kube-green-placeholder
    group_by:
      - alertname
      - service
      - env
      - severity
    group_wait: 30s
    group_interval: 10m
    repeat_interval: 12h
    routes:
      - receiver: slack-kube-green-placeholder
        object_matchers:
          - ["service", "=", "kube-green"]
          - ["env", "=", "dev"]
        group_by:
          - alertname
          - service
          - env
          - severity
        group_wait: 30s
        group_interval: 10m
        repeat_interval: 12h
