---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hivewiki-collector-prod-secret
  namespace: hivewiki-collector-prod
spec:
  encryptedData:
    DB_PASSWORD: AgDD6HC9SBJxC6jVE9Oa9mjrpQX7AWKG1arWW2ddDh7jl59h5fFk0u2/fINJGsRKlq6/ELXDZbsLx3XyE1mKEm4y0LRkkO49BteVXa18YBoqvAY09TpVckvUiHOEJ7nruBM463H9bV7d99Nx7biBg+vXK1+FSsFm2VdnaqAcSX6iFp+nDR6DjxTuZJT5S7Qg7cKz76uEMKnY3MI7RF1d0zDnuP8KD5TPs3/Rl0kG8XoFOG8fZojeVSVKM9blopsFii2k0DuNdtWXs4emhtPAZZc27YvCyP1uGxO3xtzFaiplpDGgkykGi66PJICgjVU9W590mmT+kTUa/SE4uL9XiR5SODPQbBkz6aOYUnPEoxg/87qHGhA9a7zKVNPguD8+zuBhGqMy+BU+KxTWRsX4fBv53RV46MAY15HjnyCByTP8TGu964NNLXRKxOIObLz1NyLETppkr0zw4eLf8BUDnlc6SaUjMMPvY55eof0gQcGT9igBJj0Ce/vacP3kcuU+yqoxbgkd8bCnBIg8iK3ablEE0CR9NtRoX8GLpK1bF9BZDEqQ8a0MQdwPQN+oiC6IJP+6LplFSc3dt/GOe4IiGRxoFYnAUqvaVbU07p/gH3RF1jOLjKbN46g2i8jA1ZJGcNaHeXGM9FtsdGbRZxHJcoIHqi6t7sYBVXRRtjibST9TPOt6dPJGeQ4uhd24l3nmCfjKVguiiSk6WGfbme3t
    REDIS_URL: AgDQx4t9M40pgL3jm96/45oDsJbiOK4q18BP4h+570EG3wQf70t64kaaP9DSqYwcOtDwFiZGS3yv2rVhuzsNsH0gWfVDBRk9ErUGHBMYzlSQwtBSC8MO1l4tVj8isgwr8iZW2nP4IZpbRsHZX7YENxg1czLjVx9FCK9qXECpiitL592rq2MJzUmI0orURfzLe/7chtakFjdcFbFWNZrQPJdb8sKfBkT86YDX8+H9PL0zi0SeAHQs9C2GHNdKf5b0Iu5aX7mF90c1udiPuAwCiCEmtzy32fc54pLo94Zi1jmH5LkdReZRtYmrBNG1UXWXtNEa063dV61CU3GILXo8bzdjqRlDtYdbvXVu+hlc/VR1sN+wFxuewUbtXujT1rhYF+7hu0oE5pcPhxQPjnKT/tjkogQF1aMXHEAbLW5ajpPjomhikYu1+Ku83d2whkYg9p4oKes8/bgUVWnNteHR0mH8FTcyhzu0Sm5Aq0CMAaSjMs/QaUKpn00opLQpuuGuHSbNfZE9XSHbHwtaAU+he8IxTlIXudyG5vv2PBchQRAMO9kV1hXiNLqmvQ0YqP3riOKyQayLR9al22Zr3j/dsTRNeUECGIhundCdiEPrhVQYh2Ad4Aac68FdUw3KFRtt+IjtgEoHqeNrkRB4wZdgvSP80hobc4haZGSJfTgpAGnoghfd5B38k0U/jvl7Kapd0HqyvhnngPb+SC/CRTMx11vFtEyltk12cWiNGquuSZhfPmvCLOvZcAlhQuLicPmczM1A8AxEV9er2uuoG+UsF8UEbQ3GJAAg
  template:
    metadata:
      name: hivewiki-collector-prod-secret
      namespace: hivewiki-collector-prod
    type: Opaque
