---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCtkVee5uvxmP4aWSyi4LZ52gmVkCycn/AeyLhkazBaiuFxGzPlh4yt6acQPMGgylO6A4SBSauoYkT5BP3rf8kPzLquuWsV3E+j/WP9OUxBM1k8pd2HX4CqimURN92c0qQSunzvz20MG3bb2N+choh9BzsXQMsC1XxfkTx+3x/ROohy7wifb/QZ+Pvmm5H6apWDS4/N3h3E2KPgnLzfb9UjGrrargEYINRkVl6DSqMsvNVTzJ/YCPIGk2Py5s+YU64zcpWNMIT5Z1Yg9V4poIfLVU815nifOdlWdgtZ+Jm5ID6cR/OzPuNF0sjs5vplAz0uYslY0uZ3nhG02/NIMe1+nja5Ea23F7N3D77OHo/6lQD5oxco7zHEEAunXtiWrC3Hp5I/0GAcQAYmuz+SOP6XT0Gkz8XwLseTxYnMoBpUA78WQ1iLnZWsnqlOZyqsGGhFCYDEajHU4vTQEn17uNBimqEQl8lGXwpVA03n9uHIx9GTtdiEqKfYmrhuOXgWaYAYA2VF1uNA7d9MHbFif7madMj+kp3cMEzdxZvjls1+RWKzyjbbH6mwAM64e11DdPUr0sIV4ODOxedpc/rePJGQtYd62JEwX6M7oiuBQt/KskwRTO882CiB27uDw1in6nbmPB2Z/jWt4/3nyMv443j9AA0+8QgZUP8gLCWG6CPhDARwzNz1NFxoq5OQyVwCmywrDzCewPx8vApxZBlWbqxTVMAEagzMgthAFrPzyXvipZstsrXzbWLYPrRrEwWtcqTBb4f3A5Gb17HcFzOGOqgveP+zwQXHC8+yutq4odCEgnE=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
    type: Opaque
