configmapReload:
  prometheus:
    image:
      repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/quay/prometheus-operator/prometheus-config-reloader
      tag: v0.91.0
      pullPolicy: IfNotPresent

server:
  image:
    repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/quay/prometheus/prometheus
    pullPolicy: IfNotPresent
  persistentVolume:
    storageClass: gp3

alertmanager:
  image:
    repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/quay/prometheus/alertmanager
    pullPolicy: IfNotPresent
  persistence:
    storageClass: gp3

kube-state-metrics:
  image:
    registry: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com
    repository: k8s/kube-state-metrics/kube-state-metrics
    pullPolicy: IfNotPresent

prometheus-node-exporter:
  image:
    registry: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com
    repository: quay/prometheus/node-exporter
    pullPolicy: IfNotPresent

prometheus-pushgateway:
  image:
    repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/quay/prometheus/pushgateway
    pullPolicy: IfNotPresent

extraScrapeConfigs: |
  - job_name: yace
    scrape_interval: 15s
    scrape_timeout: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - yace-prometheus-yet-another-cloudwatch-exporter.monitoring.svc.cluster.local:80
  - job_name: karpenter
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - karpenter.karpenter.svc.cluster.local:8080
  - job_name: argocd
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - argocd-server-metrics.argocd.svc.cluster.local:8083
