apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: alb-config
  namespace: kube-system
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: arn:aws:acm:ap-northeast-2:647502392199:certificate/7ada3013-3056-4fca-9d5b-942153961717
      sslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
  wafV2:
    webACL: arn:aws:wafv2:ap-northeast-2:647502392199:regional/webacl/hivewiki-dev-web-acl/56fc85f7-7040-4ab4-8979-72cbbe8f58fc
  loadBalancerAttributes:
    - key: access_logs.s3.enabled
      value: "true"
    - key: access_logs.s3.bucket
      value: hivewiki-dev-alb-gw-logs
    - key: access_logs.s3.prefix
      value: ""
