apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hivewiki-web
  namespace: hivewiki-web-prod
spec:
  endpointSelector:
    matchLabels:
      app: hivewiki-web
      app.kubernetes.io/name: hivewiki-web
      app.kubernetes.io/part-of: hivewiki
      environment: prod
  egress:
    # AWS Credentials
    - toCIDR:
      - 169.254.170.23/32
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
        - port: "80"
          protocol: TCP
    - toEntities:
      - host
      toPorts:
      - ports:
        - port: "80"
          protocol: TCP
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: s3.ap-northeast-2.amazonaws.com
      - matchPattern: "*.s3.ap-northeast-2.amazonaws.com"
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: openidconnect.googleapis.com
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: oauth2.googleapis.com
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: api.github.com
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: github.com
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP
    - toFQDNs:
      - matchName: hivewiki-prod-mdqrku.serverless.apn2.cache.amazonaws.com
      toPorts:
      - ports:
        - port: "6379"
          protocol: TCP
    - toFQDNs:
      - matchName: hivewiki-prod.c7kkg8a0sdsw.ap-northeast-2.rds.amazonaws.com
      toPorts:
      - ports:
        - port: "5432"
          protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
