apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivewiki-web-prod

resources:
  - ../../base
  - ciliumnetworkpolicy.yaml
  - namespace.yaml
  - sealedsecret.yaml

patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-httproute.yaml
  - path: patch-serviceaccount.yaml

images:
  - name: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/hivewiki-web
    newTag: prod-7efa614
