apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivewiki-web
  labels:
    environment: prod
spec:
  selector:
    matchLabels:
      environment: prod
  template:
    metadata:
      labels:
        environment: prod
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        env: prod
        workload: app
        nodepool: prod
      tolerations:
        - key: env
          operator: Equal
          value: prod
          effect: NoSchedule
      containers:
        - name: hivewiki-web
          startupProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: www.hive-wiki.com
                - name: X-Forwarded-Proto
                  value: https
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: www.hive-wiki.com
                - name: X-Forwarded-Proto
                  value: https
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: www.hive-wiki.com
                - name: X-Forwarded-Proto
                  value: https
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
