apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hivewiki-web
  labels:
    environment: dev
spec:
  parentRefs:
    - name: my-alb-gateway
      namespace: kube-system
      sectionName: http-dev
    - name: my-alb-gateway
      namespace: kube-system
      sectionName: https-dev
  hostnames:
    - test.hive-wiki.com
