apiVersion: v1
kind: ConfigMap
metadata:
  name: hivewiki-web-env
data:
  DJANGO_ALLOWED_HOSTS: "test.hive-wiki.com,hivewiki-web.hivewiki-web-dev.svc.cluster.local"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://test.hive-wiki.com"
