{
 "title": "YACE",
 "description": "Dashboard for the yet-another-cloudwatch-exporter(https://github.com/nerdswords/yet-another-cloudwatch-exporter) exporter scraping AWS resources.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "ApplicationELB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Target Response Time Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_applicationelb_target_response_time_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Target Response Time p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_applicationelb_target_response_time_p95",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "ELB 5XX Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_elb_5_xx_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Target 5XX Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_5_xx_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_healthy_host_count_minimum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_un_healthy_host_count_maximum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Target Connection Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_target_connection_error_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Utilization Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_maximum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Database Connections Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Database Connections Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_maximum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Freeable Memory Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Free Storage Space Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Read Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Write Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_write_latency_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Read IOPS Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "aws_rds_read_iops_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Write IOPS Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "aws_rds_write_iops_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "ElastiCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "CPU Utilization Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Engine CPU Utilization Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_engine_cpuutilization_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_database_memory_usage_percentage_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Current Connections Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elasticache_curr_connections_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elasticache_cache_hits_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elasticache_cache_misses_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elasticache_evictions_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Replication Lag Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_elasticache_replication_lag_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "NATGateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Active Connection Count Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_active_connection_count_maximum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Bytes In From Destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_in_from_destination_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Bytes Out To Destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_out_to_destination_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Packets Drop Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_drop_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Error Port Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_error_port_allocation_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Idle Timeout Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_idle_timeout_count_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "CloudFront", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cloudfront_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Bytes Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_cloudfront_bytes_downloaded_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Bytes Uploaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_cloudfront_bytes_uploaded_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_cloudfront_total_error_rate_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_cloudfront_4xx_error_rate_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_cloudfront_5xx_error_rate_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Bucket Size Bytes Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_s3_bucket_size_bytes_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Number Of Objects Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  { "title": "WAFV2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_wafv2_allowed_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_wafv2_blocked_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Counted Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_wafv2_counted_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Captcha Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_wafv2_captcha_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  },
  {
   "title": "Challenge Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_wafv2_challenge_requests_sum",
     "legendFormat": "{{dimension_Name}}{{dimension_LoadBalancer}}{{dimension_TargetGroup}}{{dimension_DBInstanceIdentifier}}{{dimension_CacheClusterId}}{{dimension_NatGatewayId}}{{dimension_DistributionId}}{{dimension_BucketName}}{{dimension_WebACL}}"
    }
   ]
  }
 ]
}