apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivewiki-builder-prod

resources:
  - ../../base
  - namespace.yaml
  - sealedsecrets.yaml
  - serviceaccount.yaml

patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml

images:
  - name: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/hivewiki-builder
    newTag: prod-7092866
