apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivewiki-builder
  labels:
    environment: prod
spec:
  selector:
    matchLabels:
      environment: prod
  template:
    metadata:
      labels:
        environment: prod
    spec:
      nodeSelector:
        env: prod
        workload: app
        nodepool: prod
      tolerations:
        - key: env
          operator: Equal
          value: prod
          effect: NoSchedule
      containers:
        - name: hivewiki-builder
          env:
            - name: HOME
              value: /tmp
            - name: USER
              value: app
            - name: LOGNAME
              value: app
            - name: STORM_WORK_DIR
              value: /tmp/hivewiki-builder/storm
            - name: DSP_CACHEDIR
              value: /tmp/hivewiki-builder/dsp-cache
            - name: TORCHINDUCTOR_CACHE_DIR
              value: /tmp/hivewiki-builder/torchinductor-cache
            - name: XDG_CACHE_HOME
              value: /tmp/hivewiki-builder/.cache
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
