image:
  repository: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com/quay/argoprojlabs/argocd-image-updater
  pullPolicy: IfNotPresent

config:
  log.level: debug
  registries:
   - name: ECR
     api_url: https://647502392199.dkr.ecr.ap-northeast-2.amazonaws.com
     prefix: 647502392199.dkr.ecr.ap-northeast-2.amazonaws.com
     credentials: ext:/scripts/ecr-login.sh
     credsexpire: 10h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      aws ecr get-authorization-token \
        --region ap-northeast-2 \
        --output text \
        --query 'authorizationData[].authorizationToken' | base64 -d

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

serviceAccount:
  create: true
  name: argocd-image-updater

nodeSelector:
  env: shared
  workload: system
