apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-green
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/Hallym-Workerbees/hivewiki-gitops
      targetRevision: main
      ref: values

    - repoURL: https://kube-green.github.io/helm-charts/
      chart: kube-green
      targetRevision: 0.7.1
      helm:
        releaseName: kube-green
        valueFiles:
          - $values/infra/kube-green/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-green

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
